name: AeroWave Kani Verification

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Setup Kani Rust Verifier
        uses: model-checking/kani-github-action@v0.32
        env:
          CARGO_MANIFEST_DIR: .
          CARGO_TARGET_DIR: ./target
        with:
          args: --manifest-path ./Cargo.toml
