name: AeroWave Kani Verification

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install Latest Stable Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          override: true

      - name: Install and Execute Kani Verifier Natively
        run: |
          cargo install --locked kani-verifier
          cargo kani setup
          cargo kani --manifest-path ./Cargo.toml
